// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spslkeczsmwbkddinsgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwc2xrZWN6c213YmtkZGluc2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTA5MDgsImV4cCI6MjA1Njc4NjkwOH0.CI7V3Wspri-a-inizHGyFtPgXDcR75918W-kvpcWoW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);