// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxqllafguhuntaykvkud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14cWxsYWZndWh1bnRheWt2a3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDM2NDMsImV4cCI6MjA1NjUxOTY0M30.MclBzHp3NJ0BdlM8GYTcAoGnvZo1QDDDPIxdqBez754";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);